name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update.py

      - name: Debug GH_TOKEN
        run: echo "GH_TOKEN is ${GH_TOKEN:0:4}************"
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name 'kennethcassel'
          git config --global user.email 'kennethcassel@gmail.com'
          git add README.md
          git commit -m "Update README with purchase links"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
